Add a prune-nitro command

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -235,6 +235,7 @@ check_disk_space() {
     if [[ "${value}" =~ "arbitrum.yml" ]] && [[ "${__free_space}" -lt 104857600 ]]; then
         echo ""
         echo "You are running Arbitrum and have less than 100 GiB of free disk space."
+        echo "If Avail reads 40 GiB or more, prune with ./ethd prune-nitro:"
         echo ""
         df -h "${__docker_dir}"
         echo ""
@@ -435,6 +436,113 @@ cmd() {
     docompose "$@"
 }
 
+prune-nitro() {
+    __non_interactive=0
+    while :
+    do
+        if [ -z ${1+x} ]; then
+            break
+        fi
+        case "$1" in
+            --non-interactive)
+                __non_interactive=1
+                shift
+                ;;
+            *)
+                echo "Error: Unknown option: $1" >&2
+                exit 1
+                ;;
+        esac
+    done
+
+    if [ ! -f "./${ENV_FILE}" ]; then
+        echo "${ENV_FILE} configuration file not found, aborting."
+        exit 1
+    fi
+
+    if ! grep -q '^COMPOSE_FILE=.*arbitrum\.yml' "${ENV_FILE}" 2>/dev/null ; then
+        echo "You do not appear to be using Nitro, aborting."
+        exit 1
+    fi
+
+    __docker_dir=$(docker system info --format '{{.DockerRootDir}}')
+
+    if [ "$(df -P ${__docker_dir} | awk '/[0-9]%/{print $(NF-2)}')" -lt 41943040 ]; then
+        echo "You do not have enough free disk space. Make sure this reads at least 40G free (Avail):"
+        df -h "${__docker_dir}"
+        echo ""
+        echo "Aborting."
+        exit 1
+    fi
+
+    rpc_line=$(grep '^RPC_PORT=' "${ENV_FILE}")
+    regex='^RPC_PORT=([0-9]+)'
+    if [[ ! "${rpc_line}" =~ ${regex} ]]; then
+        echo "Unable to determine RPC_PORT, aborting."
+        exit 1
+    else
+        rpc_port="${BASH_REMATCH[1]}"
+    fi
+
+    sync_status=$(docompose exec -T nitro wget -qO- "http://localhost:$rpc_port" --header 'Content-Type: application/json' --post-data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}')
+    exitstatus=$?
+    if [ $exitstatus -ne 0 ]; then
+        echo "Unable to connect to Nitro: Is it running?"
+        echo "Output: ${sync_status}"
+        echo "Aborting."
+        exit 1
+    fi
+
+    if [[ ! "${sync_status}" =~ "false" ]]; then
+        echo "Nitro is not done syncing yet. Sync status:"
+        echo "${sync_status}"
+        echo ""
+        echo "Aborting."
+    fi
+
+    node_logs=$(docompose logs --no-color --tail 1000 nitro)
+    if [[ "${node_logs}" =~ "snapshot generation" && ! "${node_logs}" =~ "Generated state" ]]; then
+        echo "Nitro has not finished generating a state snapshot yet, aborting."
+        exit 1
+    fi
+
+    regex='\[([0-9][0-9]-[0-9][0-9])\|([0-9][0-9]:[0-9][0-9]):[0-9.]*\][[:space:]]*Generated state'
+    if [[ "${node_logs}" =~ $regex ]]; then
+        snap_time=$(date -d "1970-${BASH_REMATCH[1]} ${BASH_REMATCH[2]}" +"%s")
+        now_time=$(date +"%s")
+        if [ $((snap_time+2100)) -gt "$now_time" ]; then
+            echo "Please wait 35 minutes after snapshot generation finished. Aborting."
+            exit 1
+        fi
+    fi
+
+    if [ $__non_interactive = 0 ]; then
+      while true; do
+          read -rp "WARNING - this will stop Nitro and prune its database. Do you wish to continue? (No/Yes) " yn
+          case $yn in
+              [Yy][Ee][Ss] ) break;;
+              * ) echo "Aborting, no changes made"; exit 1;;
+          esac
+      done
+    fi
+
+    echo ""
+    echo "Starting Nitro prune"
+    echo ""
+    docompose run --rm set-prune-marker "touch /var/lib/nitro/prune-marker"
+    docompose stop nitro && docompose rm -f nitro
+    start
+    echo ""
+    echo "Prune is running, you can observe it with './ethd logs -f nitro'"
+    echo ""
+    echo "There should be three stages: \"Iterating state snapshot\", \"Pruning state data\", and \"Compacting database\". During \
+the \"Compacting database\" stage it may not output logs for an hour or so, that is normal."
+    echo ""
+    echo "When prune is done, Nitro will automatically start again."
+    echo ""
+}
+
+
 set_value_in_env() {
     # Assumes that "var" has been set to the name of the variable to be changed
     if [ "${!var+x}" ]; then
@@ -489,6 +597,8 @@ printhelp() {
     echo "     executes an arbitrary docker compose command. Use \"cmd help\" to list them"
     echo "  terminate"
     echo "     stops the Arbitrum node and destroys all data stores"
+    echo "  prune-nitro"
+    echo "     stops the nitro client and prunes its DB."
     echo ""
     echo "The logs subcommand can be appended by flags and specify the container(s). example: "
     echo ""
